export enum SANDBOX_CONTEXT_ACTIONS {
  SELECT_PROBLEM_STATEMENT = "SELECT_PROBLEM_STATEMENT",
  IS_PROBLEM_STATEMENT_LOADING = "IS_PROBLEM_STATEMENT_LOADING",
  EXECUTE_SOLUTION = "EXECUTE_SOLUTION",
  SUBMIT_SOLUTION = "SUBMIT_SOLUTION",
  IS_SOLUTION_EXECUTING = "IS_SOLUTION_EXECUTING",
  IS_SOLUTION_SUBMITTING = "IS_SOLUTION_SUBMITTING",
}
